require("prototypes.categories.crushing")
require("prototypes.ores.generator")
require("prototypes.items.crushed-ores.iron.data")
require("prototypes.items.plates.iron.data")
require("prototypes.buildings.data")
