require("prototypes.categories.crushing")
require("prototypes.ores.generator")
require("prototypes.items.crushed-ores.data")
require("prototypes.items.plates.data")
require("prototypes.buildings.data")
