name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
  - type: input
    id: factorio_version
    attributes:
      label: Factorio version
    validations:
      required: true
  - type: input
    id: mod_version
    attributes:
      label: Mod version
    validations:
      required: true
