data:extend({
  {
    type = "container",
    name = "friction-data-analyzer",
    localised_name = { "entity-name.friction-data-analyzer" },
    localised_description = { "entity-description.friction-data-analyzer" },
    icon = "__Friction__/graphics/icons/buildings/crusher.png",
    icon_size = 64,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "friction-data-analyzer" },
    max_health = 150,
    corpse = "small-remnants",
    collision_box = { { -0.7, -0.7 }, { 0.7, 0.7 } },
    selection_box = { { -1, -1 }, { 1, 1 } },
    inventory_size = 2,
    supply_area_distance = 50,
    picture = {
      filename = "__Friction__/graphics/entity/buildings/crusher.png",
      priority = "extra-high",
      width = 256,
      height = 256,
      shift = { -0.25 / 32, 6 / 32 },
      scale = 0.5,
    },
  },
})
