name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - '.github/**'
      - '*.md'
      - 'LICENSE'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  release-please:
    name: Release please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      # - uses: actions/create-github-app-token@v1
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547
        id: generate_token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      # - uses: googleapis/release-please-action@v4
      - uses: googleapis/release-please-action@c3fc4de07084f75a2b61a5b933069bda6edf3d5c
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ steps.generate_token.outputs.token }}

  upload-mod:
    name: Upload mod zip
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build zip
        run: |
          zip -r Friction_${{ needs.release-please.outputs.tag_name }}.zip . \
            --exclude=".git/*" \
            --exclude=".github/*" \
            --exclude="*.md" \
            --exclude="LICENSE"

      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            Friction_${{ needs.release-please.outputs.tag_name }}.zip
